/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-07-13 07:36:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.placeOrder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mcdelivery.model.Product;
import java.util.List;
import mcdelivery.controller.facade.ProductFacade;
import mcdelivery.model.Customer;

public final class orderForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("mcdelivery.model.Customer");
    _jspx_imports_classes.add("mcdelivery.controller.facade.ProductFacade");
    _jspx_imports_classes.add("mcdelivery.model.Product");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	// Get the customer from session
	Customer customer = (Customer) request.getSession().getAttribute("customer");

	// Get the product list from database
	ProductFacade productFacade = new ProductFacade();
	List<Product> products = productFacade.selectProducts();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Order Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h1>McDelivery Home Page</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<span style=\"font-size:20px;\">");
      out.print( customer.getUsername() );
      out.write("</span>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"../logout/logoutServlet\" style=\"font-size:20px; float:right;\"><button>Logout</button></a>\r\n");
      out.write("\t\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\tSelect one of the item and specify the quantity of the selected item.<br> \r\n");
      out.write("\t\tClick the <b>McWallet Balance</b> to reload McWallet.<br>\r\n");
      out.write("\t\tClick <b>Add to Cart</b> to add product into cart.<br>\r\n");
      out.write("\t\tClick <b>Check Out Order</b> to calculate the total amount of order.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<p style=\"text-align:right;\">\r\n");
      out.write("\t\t<a href=\"../reloadMcWallet/reloadMcWalletServlet\">\r\n");
      out.write("\t\t\tMcWallet Balance: RM ");
      out.print( String.format("%.2f", customer.getMcWalletBalance()) );
      out.write("\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"font-size:20px\"><b>Current Ordered Product: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberOfOrder}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></div>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"placeOrderServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<p style=\"font-size:18px\">Please select a product and enter the quantity :</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t");
 for(Product product : products) { 
      out.write("\r\n");
      out.write("\t\t\t");
 int productId = product.getId(); 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<tr title=\"");
      out.print( product.getType().getName() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<td><input type=\"radio\" id=\"");
      out.print( productId );
      out.write("\" name=\"product\" value=\"");
      out.print( productId );
      out.write("\" required></td> \r\n");
      out.write("\t\t\t\t\t<td><label for=\"");
      out.print( productId );
      out.write('"');
      out.write('>');
      out.print( product.getName() );
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"");
      out.print( productId );
      out.write("\"> - RM ");
      out.print( String.format("%.2f", product.getPrice()) );
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</table><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label for=\"quantity\">Quantity: </label>\r\n");
      out.write("\t\t<input type=\"number\" id=\"quantity\" name=\"quantity\" min=\"1\" required title=\"Quantity of product\"><br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Add to Cart\"> &nbsp;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"checkOutServlet\"><button type=\"button\">Check Out Order</button></a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form><br>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
